[book]
title = "ROHI SDK"
authors = ["Akagi Engineering"]
language = "en"
multilingual = false
src = "."

[output.html]
git-repository-url = "https://github.com/akagi-dev/rohi-sdk"

[rust]
edition = "2021"
